.build-linux-dev:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - cd dev/${CI_JOB_NAME%-dev}
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/$CI_JOB_NAME:latest .
    - docker push $CI_REGISTRY_IMAGE/$CI_JOB_NAME:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_TYPE == "dev"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual

centos-7-dev:
  extends: .build-linux-dev

centos-8-dev:
  extends: .build-linux-dev

debian-stable-dev:
  extends: .build-linux-dev

fedora-dev:
  extends: .build-linux-dev

opensuse-15.2-dev:
  extends: .build-linux-dev

opensuse-15.1-dev:
  extends: .build-linux-dev

ubuntu-dev:
  extends: .build-linux-dev

# XXX windows?
