centos-8-dev:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - cd dev/$CI_JOB_NAME
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/$CI_JOB_NAME:latest .
    - docker push $CI_REGISTRY_IMAGE/$CI_JOB_NAME:latest

opensuse-15.2-dev:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - cd dev/$CI_JOB_NAME
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/$CI_JOB_NAME:latest .
    - docker push $CI_REGISTRY_IMAGE/$CI_JOB_NAME:latest
